### ISSUE TITLE
Team Page Not Displaying Correctly

### ISSUE THREAD

**Issue by Abdo-Nsila** [kouralink/web-client#187]
When I go to view the team page from the tournament team list, sometimes I get an error in this line :

https://github.com/kouralink/web-client/blob/8f9e1f218ebb1826e6e2f45186182da43df2a273/src/components/global/cards/MatchRecordCardIteam.tsx#L73

**Comment by Abdo-Nsila** [comment]
![Uploading from team page.png…]()

**Comment by Abdo-Nsila** [comment]
![issue match card](https://github.com/kouralink/web-client/assets/126418751/d572cb93-8884-469c-ac70-5dd7af9f9b51)

**Comment by Abdo-Nsila** [comment]
I found a solution to the issue we were facing. However, I'm not sure if this is the most efficient solution. 
Here's what I did:


```ts
<AvatarFallback>{props.team2.name?.charAt(0)}</AvatarFallback>
```

I have add a => ? , hhhhhh
but you must review this problem...

**Comment by Abdo-Nsila** [comment]
## It is same like this is not an issue in the code itself, but a team has been deleted from firestore, and his ID is still stored in the match data, In the fetch process the team is not found anymore so some data is missing like this error the `props.team2.name` is not define . 


![no team](https://github.com/kouralink/web-client/assets/126418751/f6db1985-af88-4b13-838a-3a82671c6b3e)

**Comment by ilorez** [comment]
the problem was that the team has deleted some how, i add check for know so error will not shown again
